// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    partial class ParksLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksLookup.Models.Landmark", b =>
                {
                    b.Property<int>("LandmarkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("ParkId");

                    b.HasKey("LandmarkId");

                    b.HasIndex("ParkId");

                    b.ToTable("Landmark");

                    b.HasData(
                        new
                        {
                            LandmarkId = 1,
                            Name = "Yosemite Valley",
                            ParkId = 1
                        },
                        new
                        {
                            LandmarkId = 2,
                            Name = "Half Dome",
                            ParkId = 1
                        },
                        new
                        {
                            LandmarkId = 3,
                            Name = "YosemiteFalls",
                            ParkId = 1
                        });
                });

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Hours");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhotoUrl");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Classification = "National",
                            Hours = "27/7",
                            Name = "Yosemite",
                            PhotoUrl = "www.sample.com",
                            State = "California"
                        });
                });

            modelBuilder.Entity("ParksLookup.Models.Landmark", b =>
                {
                    b.HasOne("ParksLookup.Models.Park", "Park")
                        .WithMany("Landmarks")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
